# Generated by Django 4.1.3 on 2024-03-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('courses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.course')),
                ('programming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dropdown.programming')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='programming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdown.programming'),
        ),
    ]
